#!/bin/bash
set -euo pipefail

aws sso login

cd app/libs/sim-wasm
wasm-pack build --release --target web --out-dir ../../web/src/sim-wasm-pkg
cd ../../..

cd app/web/
rm -rf dist/
npm run build
cd ../..

terraform -chdir=terraform init
terraform -chdir=terraform validate
terraform -chdir=terraform apply -auto-approve

# Invalidate CloudFront cache
aws cloudfront create-invalidation \
  --distribution-id $(terraform -chdir=terraform output -raw cloudfront_distribution_id) \
  --paths "/*" \
  --no-cli-pager

# Get variables from terraform output and export .env for Docker compose
aws_region=$(terraform -chdir=terraform output -raw aws_region)

api_ecr_repo_url=$(terraform -chdir=terraform output -raw api_ecr_repo_url)
render_ecr_repo_url=$(terraform -chdir=terraform output -raw render_ecr_repo_url)
websocket_ecr_repo_url=$(terraform -chdir=terraform output -raw websocket_ecr_repo_url)
postgres_ecr_repo_url=$(terraform -chdir=terraform output -raw postgres_ecr_repo_url)

api_instance_id=$(terraform -chdir=terraform output -raw api_instance_id)
postgres_instance_id=$(terraform -chdir=terraform output -raw postgres_instance_id)

api_private_ip=$(terraform -chdir=terraform output -raw api_private_ip)
postgres_private_ip=$(terraform -chdir=terraform output -raw postgres_private_ip)

api_port_host=$(terraform -chdir=terraform output -raw api_port_host)
api_port_container=$(terraform -chdir=terraform output -raw api_port_container)
postgres_port_host=$(terraform -chdir=terraform output -raw postgres_port_host)
postgres_port_container=$(terraform -chdir=terraform output -raw postgres_port_container)
render_port=$(terraform -chdir=terraform output -raw render_port)
websocket_port=$(terraform -chdir=terraform output -raw websocket_port)

redis_elasticache_endpoint=$(terraform -chdir=terraform output -raw redis_elasticache_endpoint)
redis_elasticache_port=$(terraform -chdir=terraform output -raw redis_elasticache_port)
cat > ".env" <<EOF
# Auto-generated by provision-infrastructure.sh: $(date -Iseconds)

AWS_REGION=${aws_region}

# ECR repositories
API_ECR_REPO_URL=${api_ecr_repo_url}
RENDER_ECR_REPO_URL=${render_ecr_repo_url}
WEBSOCKET_ECR_REPO_URL=${websocket_ecr_repo_url}
POSTGRES_ECR_REPO_URL=${postgres_ecr_repo_url}

# Instance IDs
API_INSTANCE_ID=${api_instance_id}
POSTGRES_INSTANCE_ID=${postgres_instance_id}

# Private IP addresses
API_PRIVATE_IP=${api_private_ip}
POSTGRES_PRIVATE_IP=${postgres_private_ip}

# Port maps
API_PORT_HOST=${api_port_host}
API_PORT_CONTAINER=${api_port_container}
POSTGRES_PORT_HOST=${postgres_port_host}
POSTGRES_PORT_CONTAINER=${postgres_port_container}
RENDER_PORT=${render_port}
WEBSOCKET_PORT=${websocket_port}

# ElastiCache
REDIS_ELASTICACHE_ENDPOINT=${redis_elasticache_endpoint}
REDIS_ELASTICACHE_PORT=${redis_elasticache_port}
EOF

cat > "local.env" <<EOF
# Auto-generated by provision-infrastructure.sh: $(date -Iseconds)

AWS_REGION=${aws_region}

# ECR repositories
API_ECR_REPO_URL=${api_ecr_repo_url}
RENDER_ECR_REPO_URL=${render_ecr_repo_url}
WEBSOCKET_ECR_REPO_URL=${websocket_ecr_repo_url}
POSTGRES_ECR_REPO_URL=${postgres_ecr_repo_url}

# Instance IDs
API_INSTANCE_ID=${api_instance_id}
POSTGRES_INSTANCE_ID=${postgres_instance_id}

# Private IP addresses
API_PRIVATE_IP=127.0.0.1
POSTGRES_PRIVATE_IP=127.0.0.1

# Port mapping
API_PORT_HOST=${api_port_container}
API_PORT_CONTAINER=${api_port_container}
POSTGRES_PORT_HOST=${postgres_port_container}
POSTGRES_PORT_CONTAINER=${postgres_port_container}
RENDER_PORT=${render_port}
WEBSOCKET_PORT=${websocket_port}

# ElastiCache
REDIS_ELASTICACHE_ENDPOINT=127.0.0.1
REDIS_ELASTICACHE_PORT=6379

# For local development using docker compose
POSTGRES_USERNAME=
POSTGRES_PASSWORD=
POSTGRES_DATABASE_NAME=

S3_SIMULATION_BUCKET=
SQS_RENDER_JOBS_URL=

BLENDER_PATH=/Applications/Blender.app/Contents/MacOS/blender
EOF
